export { getToken } from './authentication/getToken'
export { checkLoggedIn } from './authentication/checkLoggedIn'
export { signout } from './authentication/signout'
export { setCookie } from './authentication/setCookie'
export { removeAllCookies } from './authentication/removeAllCookies'
